In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
from google.colab import files

uploaded = files.upload()

Saving personal_finance_tracker_dataset.csv.xlsx to personal_finance_tracker_dataset.csv.xlsx

In [5]:
df = pd.read_excel(
    'personal_finance_tracker_dataset.csv.xlsx'
)

print("Dataset loaded successfully")

Dataset loaded successfully

In [6]:
print("Shape:", df.shape)

Shape: (3000, 25)

In [7]:
df.head()

,date,user_id,monthly_income,monthly_expense_total,savings_rate,budget_goal,financial_scenario,credit_score,debt_to_income_ratio,loan_payment,...,discretionary_spending,essential_spending,income_type,rent_or_mortgage,category,cash_flow_status,financial_advice_score,financial_stress_level,actual_savings,savings_goal_met
0,2019-01-01,1584,3119.58,3212.07,0.38,3676.11,inflation,721,0.56,125.77,...,857.55,1910.85,Freelance,1501.65,Investments,Positive,8.3,Low,0.00,0
1,2019-01-31,1045,3262.44,3732.81,0.10,2607.17,inflation,670,0.42,454.19,...,534.51,3165.20,Salary,1603.17,Investments,Positive,22.6,Low,0.00,0
2,2019-03-02,1756,2931.20,3335.58,0.15,3004.14,inflation,691,0.24,971.82,...,353.67,1504.56,Freelance,1097.82,Healthcare,Positive,58.8,Low,0.00,0
3,2019-04-01,1724,3506.79,2327.59,0.17,3346.97,normal,717,0.16,482.76,...,594.08,1450.72,Freelance,1155.64,Groceries,Positive,74.5,Low,1179.20,0
4,2019-05-01,1600,4606.87,2182.58,0.34,2670.09,inflation,795,0.25,263.74,...,556.86,1000.00,Salary,1170.86,Utilities,Negative,38.7,High,2424.29,0

In [8]:
df_raw = df.copy()
df_clean = df.copy()

print("Backup created.")

Backup created.

In [9]:
print(df_clean.columns.tolist())

['date', 'user_id', 'monthly_income', 'monthly_expense_total', 'savings_rate', 'budget_goal', 'financial_scenario', 'credit_score', 'debt_to_income_ratio', 'loan_payment', 'investment_amount', 'subscription_services', 'emergency_fund', 'transaction_count', 'fraud_flag', 'discretionary_spending', 'essential_spending', 'income_type', 'rent_or_mortgage', 'category', 'cash_flow_status', 'financial_advice_score', 'financial_stress_level', 'actual_savings', 'savings_goal_met']

In [10]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
)

print(df_clean.columns.tolist())

['date', 'user_id', 'monthly_income', 'monthly_expense_total', 'savings_rate', 'budget_goal', 'financial_scenario', 'credit_score', 'debt_to_income_ratio', 'loan_payment', 'investment_amount', 'subscription_services', 'emergency_fund', 'transaction_count', 'fraud_flag', 'discretionary_spending', 'essential_spending', 'income_type', 'rent_or_mortgage', 'category', 'cash_flow_status', 'financial_advice_score', 'financial_stress_level', 'actual_savings', 'savings_goal_met']

In [11]:
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])

df_clean.info()

Rows: 3000
Columns: 25
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    3000 non-null   datetime64[ns]
 1   user_id                 3000 non-null   int64
 2   monthly_income          3000 non-null   float64
 3   monthly_expense_total   3000 non-null   float64
 4   savings_rate            3000 non-null   float64
 5   budget_goal             3000 non-null   float64
 6   financial_scenario      3000 non-null   object
 7   credit_score            3000 non-null   int64
 8   debt_to_income_ratio    3000 non-null   float64
 9   loan_payment            3000 non-null   float64
 10  investment_amount       3000 non-null   float64
 11  subscription_services   3000 non-null   int64
 12  emergency_fund          3000 non-null   float64
 13  transaction_count       3000 non-null   int64
 14  fraud_flag              3000 non-null   int64
 15  discretionary_spending  3000 non-null   float64
 16  essential_spending      3000 non-null   float64
 17  income_type             3000 non-null   object
 18  rent_or_mortgage        3000 non-null   float64
 19  category                3000 non-null   object
 20  cash_flow_status        3000 non-null   object
 21  financial_advice_score  3000 non-null   float64
 22  financial_stress_level  3000 non-null   object
 23  actual_savings          3000 non-null   float64
 24  savings_goal_met        3000 non-null   int64
dtypes: datetime64[ns](1), float64(13), int64(6), object(5)
memory usage: 586.1+ KB

In [12]:
missing_values = df_clean.isnull().sum()

print(missing_values)
print("\nTotal missing values:", missing_values.sum())

date                      0
user_id                   0
monthly_income            0
monthly_expense_total     0
savings_rate              0
budget_goal               0
financial_scenario        0
credit_score              0
debt_to_income_ratio      0
loan_payment              0
investment_amount         0
subscription_services     0
emergency_fund            0
transaction_count         0
fraud_flag                0
discretionary_spending    0
essential_spending        0
income_type               0
rent_or_mortgage          0
category                  0
cash_flow_status          0
financial_advice_score    0
financial_stress_level    0
actual_savings            0
savings_goal_met          0
dtype: int64

Total missing values: 0

In [13]:
duplicate_count = df_clean.duplicated().sum()

print("Exact duplicate rows:", duplicate_count)

Exact duplicate rows: 0

In [14]:
user_date_duplicates = df_clean.duplicated(
    subset=['user_id', 'date'],
    keep=False
).sum()

print("Repeated user-date records:", user_date_duplicates)

Repeated user-date records: 143

In [15]:
print("Exact duplicate rows:", df_clean.duplicated().sum())

Exact duplicate rows: 0

In [16]:
repeated_records = df_clean[
    df_clean.duplicated(
        subset=['user_id', 'date'],
        keep=False
    )
].sort_values(['user_id', 'date'])

display(repeated_records.head(30))

,date,user_id,monthly_income,monthly_expense_total,savings_rate,budget_goal,financial_scenario,credit_score,debt_to_income_ratio,loan_payment,...,discretionary_spending,essential_spending,income_type,rent_or_mortgage,category,cash_flow_status,financial_advice_score,financial_stress_level,actual_savings,savings_goal_met
1040,2020-08-23,1029,6619.89,3812.53,0.05,2364.64,normal,722,0.32,514.94,...,496.00,1881.06,Salary,1111.14,Groceries,Positive,46.8,Low,2807.36,1
1340,2020-08-23,1029,6190.05,2737.46,0.14,2822.84,normal,659,0.26,655.51,...,535.72,2663.23,Salary,1074.89,Investments,Neutral,35.5,Low,3452.59,1
427,2019-07-30,1034,3880.74,3054.91,0.11,2444.30,inflation,698,0.37,630.20,...,705.38,1554.28,Salary,2252.27,Healthcare,Neutral,11.8,Medium,825.83,0
1387,2019-07-30,1034,4269.91,2400.56,0.21,3058.57,recession,660,0.39,150.18,...,272.11,2269.58,Salary,1179.84,Rent,Positive,88.7,Medium,1869.35,0
2509,2023-01-10,1044,4077.02,3147.04,0.12,2490.08,normal,696,0.30,415.54,...,463.44,3050.77,Salary,1045.68,Dining Out,Negative,86.1,High,929.98,0
2989,2023-01-10,1044,4501.42,2668.71,0.29,2276.92,recession,716,0.25,707.37,...,525.57,2174.65,Mixed,934.37,Utilities,Negative,11.9,Medium,1832.71,0
1058,2022-02-14,1047,2963.77,3715.67,0.24,3239.80,inflation,631,0.45,445.48,...,129.80,1851.71,Freelance,1325.53,Healthcare,Positive,37.7,Low,0.00,0
2378,2022-02-14,1047,4356.51,3613.41,0.38,2880.88,inflation,704,0.36,668.37,...,593.81,1245.93,Salary,1270.69,Insurance,Negative,12.7,Low,743.10,0
147,2021-03-21,1109,4870.59,3461.87,0.22,2200.37,inflation,643,0.25,371.28,...,254.78,1622.42,Salary,1256.79,Entertainment,Positive,15.9,Low,1408.72,0
2007,2021-03-21,1109,2880.23,2783.31,0.16,2630.59,normal,579,0.20,340.58,...,372.26,3117.54,Salary,1131.94,Dining Out,Positive,86.0,Medium,96.92,0
1431,2023-03-11,1113,4309.59,3037.69,0.36,2164.24,recession,738,0.12,538.70,...,811.17,2009.16,Salary,910.32,Dining Out,Positive,29.5,Medium,1271.90,0
2991,2023-03-11,1113,3595.80,4349.94,0.15,2894.59,inflation,649,0.47,453.89,...,483.73,1739.46,Salary,1642.40,Utilities,Positive,28.9,Low,0.00,0
1258,2023-10-07,1126,4832.32,3022.15,0.35,2763.64,recession,670,0.17,376.52,...,290.22,1370.30,Mixed,1585.73,Investments,Positive,26.1,Medium,1810.17,0
2038,2023-10-07,1126,5446.46,2191.78,0.19,3530.29,normal,615,0.11,141.47,...,614.68,2542.08,Salary,865.50,Investments,Positive,76.3,Low,3254.68,0
1831,2021-07-19,1148,4615.70,3231.27,0.37,3021.24,normal,661,0.11,153.50,...,228.43,1757.32,Salary,428.90,Groceries,Positive,55.6,High,1384.43,0
2851,2021-07-19,1148,3715.31,3449.86,0.12,2880.33,normal,686,0.23,572.62,...,347.39,1971.13,Salary,841.69,Investments,Neutral,41.2,Low,265.45,0
270,2021-06-19,1158,3652.62,3357.22,0.26,2534.24,normal,637,0.56,125.84,...,343.91,2069.21,Salary,441.35,Rent,Positive,1.3,Low,295.40,0
2310,2021-06-19,1158,3367.43,2730.80,0.20,3056.91,normal,684,0.23,271.27,...,574.79,2215.08,Mixed,1051.34,Insurance,Negative,42.8,High,636.63,0
1715,2021-11-16,1164,3935.93,3685.76,0.22,2010.51,inflation,666,0.41,534.66,...,707.43,2719.58,Mixed,1565.65,Groceries,Negative,79.7,Low,250.17,0
1955,2021-11-16,1164,4150.90,4123.76,0.31,2104.00,normal,590,0.45,549.60,...,451.85,1494.24,Freelance,1148.66,Education,Neutral,87.4,Medium,27.14,0
1946,2021-02-19,1171,5030.81,2784.06,0.33,2355.92,inflation,664,0.37,655.70,...,550.36,2244.91,Salary,1236.95,Rent,Negative,70.8,Low,2246.75,0
2246,2021-02-19,1171,3353.20,2892.26,0.33,2418.31,normal,730,0.43,900.04,...,305.76,1759.46,Salary,1470.17,Utilities,Positive,16.6,Low,460.94,0
999,2022-03-16,1171,4297.09,3052.68,0.38,3429.00,normal,666,0.40,550.85,...,611.27,1799.55,Salary,982.23,Utilities,Negative,87.9,Medium,1244.41,0
2859,2022-03-16,1171,4718.97,3348.12,0.28,3399.58,normal,713,0.37,552.89,...,514.05,1995.95,Salary,750.60,Education,Positive,57.8,High,1370.85,0
1752,2019-12-27,1190,3459.71,3007.72,0.27,2128.75,normal,674,0.50,311.31,...,439.20,2412.54,Salary,850.78,Transportation,Positive,57.4,Low,451.99,0
2532,2019-12-27,1190,4254.03,2610.84,0.33,2544.98,normal,559,0.46,588.76,...,692.08,2794.27,Salary,843.64,Rent,Positive,26.0,Medium,1643.19,0
1007,2022-11-11,1219,4139.21,2260.29,0.31,3141.57,normal,706,0.22,20.53,...,645.42,2843.36,Salary,1687.51,Education,Positive,19.7,High,1878.92,0
2027,2022-11-11,1219,5665.27,2858.91,0.10,2586.39,inflation,565,0.21,573.33,...,164.85,1000.00,Salary,794.15,Utilities,Negative,39.6,Medium,2806.36,1
1429,2023-01-10,1228,2486.20,1480.99,0.11,2960.54,recession,634,0.53,575.75,...,501.54,3283.08,Salary,300.00,Healthcare,Negative,25.1,High,1005.21,0
2329,2023-01-10,1228,5214.48,2769.89,0.15,2702.97,normal,689,0.24,651.11,...,361.45,2010.90,Salary,890.51,Utilities,Positive,89.2,Low,2444.59,0

In [17]:
repeated_groups = (
    df_clean
    .groupby(['user_id', 'date'])
    .size()
    .reset_index(name='record_count')
)

repeated_groups = repeated_groups[
    repeated_groups['record_count'] > 1
]

print("Number of repeated user-date groups:", len(repeated_groups))

display(repeated_groups.head(20))

Number of repeated user-date groups: 71

     user_id       date  record_count
77      1029 2020-08-23             2
88      1034 2019-07-30             2
124     1044 2023-01-10             2
140     1047 2022-02-14             2
310     1109 2021-03-21             2
321     1113 2023-03-11             2
357     1126 2023-10-07             2
408     1148 2021-07-19             2
443     1158 2021-06-19             2
460     1164 2021-11-16             2
485     1171 2021-02-19             2
487     1171 2022-03-16             2
544     1190 2019-12-27             2
648     1219 2022-11-11             2
682     1228 2023-01-10             2
698     1237 2020-09-22             2
715     1243 2022-04-15             2
735     1250 2023-05-10             2
763     1260 2023-10-07             2
792     1271 2021-10-17             2

In [18]:
print("Exact duplicates:", df_clean.duplicated().sum())

display(
    repeated_records[
        [
            'user_id',
            'date',
            'monthly_income',
            'monthly_expense_total',
            'transaction_count',
            'category',
            'actual_savings',
            'savings_goal_met'
        ]
    ].head(30)
)

Exact duplicates: 0

,user_id,date,monthly_income,monthly_expense_total,transaction_count,category,actual_savings,savings_goal_met
1040,1029,2020-08-23,6619.89,3812.53,82,Groceries,2807.36,1
1340,1029,2020-08-23,6190.05,2737.46,69,Investments,3452.59,1
427,1034,2019-07-30,3880.74,3054.91,39,Healthcare,825.83,0
1387,1034,2019-07-30,4269.91,2400.56,30,Rent,1869.35,0
2509,1044,2023-01-10,4077.02,3147.04,49,Dining Out,929.98,0
2989,1044,2023-01-10,4501.42,2668.71,67,Utilities,1832.71,0
1058,1047,2022-02-14,2963.77,3715.67,34,Healthcare,0.00,0
2378,1047,2022-02-14,4356.51,3613.41,55,Insurance,743.10,0
147,1109,2021-03-21,4870.59,3461.87,81,Entertainment,1408.72,0
2007,1109,2021-03-21,2880.23,2783.31,98,Dining Out,96.92,0
1431,1113,2023-03-11,4309.59,3037.69,58,Dining Out,1271.90,0
2991,1113,2023-03-11,3595.80,4349.94,45,Utilities,0.00,0
1258,1126,2023-10-07,4832.32,3022.15,55,Investments,1810.17,0
2038,1126,2023-10-07,5446.46,2191.78,85,Investments,3254.68,0
1831,1148,2021-07-19,4615.70,3231.27,73,Groceries,1384.43,0
2851,1148,2021-07-19,3715.31,3449.86,66,Investments,265.45,0
270,1158,2021-06-19,3652.62,3357.22,75,Rent,295.40,0
2310,1158,2021-06-19,3367.43,2730.80,35,Insurance,636.63,0
1715,1164,2021-11-16,3935.93,3685.76,76,Groceries,250.17,0
1955,1164,2021-11-16,4150.90,4123.76,26,Education,27.14,0
1946,1171,2021-02-19,5030.81,2784.06,47,Rent,2246.75,0
2246,1171,2021-02-19,3353.20,2892.26,81,Utilities,460.94,0
999,1171,2022-03-16,4297.09,3052.68,47,Utilities,1244.41,0
2859,1171,2022-03-16,4718.97,3348.12,86,Education,1370.85,0
1752,1190,2019-12-27,3459.71,3007.72,80,Transportation,451.99,0
2532,1190,2019-12-27,4254.03,2610.84,28,Rent,1643.19,0
1007,1219,2022-11-11,4139.21,2260.29,64,Education,1878.92,0
2027,1219,2022-11-11,5665.27,2858.91,88,Utilities,2806.36,1
1429,1228,2023-01-10,2486.20,1480.99,53,Healthcare,1005.21,0
2329,1228,2023-01-10,5214.48,2769.89,53,Utilities,2444.59,0

In [19]:
df_clean['date'] = pd.to_datetime(
    df_clean['date'],
    errors='coerce'
)

In [20]:
invalid_date_count = df_clean['date'].isnull().sum()

print("Invalid dates:", invalid_date_count)

Invalid dates: 0

In [21]:
print(df_clean['date'].dtype)

datetime64[ns]

In [22]:
categorical_columns = df_clean.select_dtypes(
    include='object'
).columns.tolist()

print("Categorical columns:", categorical_columns)

Categorical columns: ['financial_scenario', 'income_type', 'category', 'cash_flow_status', 'financial_stress_level']

In [23]:
for column in categorical_columns:
    df_clean[column] = df_clean[column].str.strip()

In [24]:
for column in categorical_columns:
    df_clean[column] = df_clean[column].str.lower()

In [25]:
for column in categorical_columns:
    print("\nColumn:", column)
    print(df_clean[column].value_counts())

Column: financial_scenario
financial_scenario
normal       1739
inflation     648
recession     613
Name: count, dtype: int64

Column: income_type
income_type
salary       2154
freelance     529
mixed         317
Name: count, dtype: int64

Column: category
category
insurance         321
utilities         320
groceries         308
healthcare        308
dining out        306
transportation    305
entertainment     291
education         289
investments       286
rent              266
Name: count, dtype: int64

Column: cash_flow_status
cash_flow_status
positive    1783
neutral      621
negative     596
Name: count, dtype: int64

Column: financial_stress_level
financial_stress_level
low       1521
medium     886
high       593
Name: count, dtype: int64

In [26]:
df_clean.describe().T

,count,mean,min,25%,50%,75%,max,std
date,3000,2021-06-04 00:00:00,2019-01-01 00:00:00,2020-03-18 12:00:00,2021-06-04 00:00:00,2022-08-20 12:00:00,2023-11-06 00:00:00,NaN
user_id,3000.0,1498.699,1000.0,1248.75,1496.5,1749.0,1999.0,287.352782
monthly_income,3000.0,4004.267347,685.28,3362.25,4008.075,4659.04,7407.94,1000.107096
monthly_expense_total,3000.0,3011.68223,159.21,2473.205,3023.81,3555.5025,5853.2,801.151864
savings_rate,3000.0,0.225897,0.05,0.14,0.23,0.31,0.4,0.101417
budget_goal,3000.0,2811.070463,1175.57,2481.9575,2822.285,3131.0,4386.5,490.855344
credit_score,3000.0,679.923667,515.0,646.0,679.0,713.0,847.0,49.970847
debt_to_income_ratio,3000.0,0.350817,0.1,0.22,0.35,0.48,0.6,0.145191
loan_payment,3000.0,508.58113,0.0,375.34,508.57,638.47,1176.88,199.44458
investment_amount,3000.0,400.610493,0.0,234.78,388.075,559.8425,1292.3,235.361273
subscription_services,3000.0,4.975,1.0,3.0,5.0,7.0,9.0,2.559536
emergency_fund,3000.0,1005.34983,0.0,674.0125,1010.485,1337.82,2585.36,485.780881
transaction_count,3000.0,59.529333,20.0,38.75,60.0,79.0,99.0,23.10161
fraud_flag,3000.0,0.023667,0.0,0.0,0.0,0.0,1.0,0.152034
discretionary_spending,3000.0,500.81099,0.0,361.5625,496.34,640.105,1158.74,199.800377
essential_spending,3000.0,2215.5871,1000.0,1807.235,2215.705,2624.675,4245.9,596.267983
rent_or_mortgage,3000.0,1211.897797,300.0,933.53,1213.605,1482.86,2614.62,400.482024
financial_advice_score,3000.0,50.071133,0.1,25.1,48.7,76.1,100.0,29.08736
actual_savings,3000.0,1156.418457,0.0,144.965,1032.81,1821.51,6589.66,1039.597384
savings_goal_met,3000.0,0.092333,0.0,0.0,0.0,0.0,1.0,0.289544

In [27]:
numeric_summary = df_clean.describe().T[['min', 'max']]

numeric_summary

                                        min                  max
date                    2019-01-01 00:00:00  2023-11-06 00:00:00
user_id                              1000.0               1999.0
monthly_income                       685.28              7407.94
monthly_expense_total                159.21               5853.2
savings_rate                           0.05                  0.4
budget_goal                         1175.57               4386.5
credit_score                          515.0                847.0
debt_to_income_ratio                    0.1                  0.6
loan_payment                            0.0              1176.88
investment_amount                       0.0               1292.3
subscription_services                   1.0                  9.0
emergency_fund                          0.0              2585.36
transaction_count                      20.0                 99.0
fraud_flag                              0.0                  1.0
discretionary_spending                  0.0              1158.74
essential_spending                   1000.0               4245.9
rent_or_mortgage                      300.0              2614.62
financial_advice_score                  0.1                100.0
actual_savings                          0.0              6589.66
savings_goal_met                        0.0                  1.0

In [28]:
non_negative_columns = [
    'user_id',
    'monthly_income',
    'monthly_expense_total',
    'budget_goal',
    'credit_score',
    'debt_to_income_ratio',
    'loan_payment',
    'investment_amount',
    'subscription_services',
    'emergency_fund',
    'transaction_count',
    'discretionary_spending',
    'essential_spending',
    'rent_or_mortgage',
    'financial_advice_score'
]

non_negative_columns = [
    column for column in non_negative_columns
    if column in df_clean.columns
]

negative_counts = (
    df_clean[non_negative_columns] < 0
).sum()

print("Negative-value count:")
print(negative_counts)

Negative-value count:
user_id                   0
monthly_income            0
monthly_expense_total     0
budget_goal               0
credit_score              0
debt_to_income_ratio      0
loan_payment              0
investment_amount         0
subscription_services     0
emergency_fund            0
transaction_count         0
discretionary_spending    0
essential_spending        0
rent_or_mortgage          0
financial_advice_score    0
dtype: int64

In [29]:
for column in non_negative_columns:
    count = (df_clean[column] < 0).sum()

    if count > 0:
        print(f"\nNegative values found in {column}: {count}")
        display(
            df_clean[df_clean[column] < 0].head()
        )

In [30]:
print("Fraud flag values:")
print(df_clean['fraud_flag'].value_counts(dropna=False))

print("\nSavings goal met values:")
print(df_clean['savings_goal_met'].value_counts(dropna=False))

Fraud flag values:
fraud_flag
0    2929
1      71
Name: count, dtype: int64

Savings goal met values:
savings_goal_met
0    2723
1     277
Name: count, dtype: int64

In [31]:
binary_columns = [
    'fraud_flag',
    'savings_goal_met'
]

for column in binary_columns:
    invalid_values = df_clean[
        ~df_clean[column].isin([0, 1])
    ]

    print(
        column,
        "- invalid rows:",
        len(invalid_values)
    )

fraud_flag - invalid rows: 0
savings_goal_met - invalid rows: 0

In [32]:
invalid_income = df_clean[
    df_clean['monthly_income'] <= 0
]

invalid_transactions = df_clean[
    df_clean['transaction_count'] < 0
]

print("Invalid income rows:", len(invalid_income))
print(
    "Invalid transaction-count rows:",
    len(invalid_transactions)
)

Invalid income rows: 0
Invalid transaction-count rows: 0

In [33]:
display(invalid_income.head())
display(invalid_transactions.head())

Empty DataFrame
Columns: [date, user_id, monthly_income, monthly_expense_total, savings_rate, budget_goal, financial_scenario, credit_score, debt_to_income_ratio, loan_payment, investment_amount, subscription_services, emergency_fund, transaction_count, fraud_flag, discretionary_spending, essential_spending, income_type, rent_or_mortgage, category, cash_flow_status, financial_advice_score, financial_stress_level, actual_savings, savings_goal_met]
Index: []

[0 rows x 25 columns]

Empty DataFrame
Columns: [date, user_id, monthly_income, monthly_expense_total, savings_rate, budget_goal, financial_scenario, credit_score, debt_to_income_ratio, loan_payment, investment_amount, subscription_services, emergency_fund, transaction_count, fraud_flag, discretionary_spending, essential_spending, income_type, rent_or_mortgage, category, cash_flow_status, financial_advice_score, financial_stress_level, actual_savings, savings_goal_met]
Index: []

[0 rows x 25 columns]

In [34]:
print(
    "Minimum credit score:",
    df_clean['credit_score'].min()
)

print(
    "Maximum credit score:",
    df_clean['credit_score'].max()
)

Minimum credit score: 515
Maximum credit score: 847

In [35]:
df_clean[
    (df_clean['credit_score'] < 300) |
    (df_clean['credit_score'] > 900)
].head()

Empty DataFrame
Columns: [date, user_id, monthly_income, monthly_expense_total, savings_rate, budget_goal, financial_scenario, credit_score, debt_to_income_ratio, loan_payment, investment_amount, subscription_services, emergency_fund, transaction_count, fraud_flag, discretionary_spending, essential_spending, income_type, rent_or_mortgage, category, cash_flow_status, financial_advice_score, financial_stress_level, actual_savings, savings_goal_met]
Index: []

[0 rows x 25 columns]

In [36]:
target_counts = df_clean[
    'savings_goal_met'
].value_counts()

target_percentage = df_clean[
    'savings_goal_met'
].value_counts(normalize=True) * 100

print("Target counts:")
print(target_counts)

print("\nTarget percentages:")
print(target_percentage.round(2))

Target counts:
savings_goal_met
0    2723
1     277
Name: count, dtype: int64

Target percentages:
savings_goal_met
0    90.77
1     9.23
Name: proportion, dtype: float64

In [37]:
print("Final Phase 1 shape:", df_clean.shape)

print(
    "Missing values:",
    df_clean.isnull().sum().sum()
)

print(
    "Duplicate rows:",
    df_clean.duplicated().sum()
)

print(
    "Invalid target values:",
    (~df_clean['savings_goal_met'].isin([0, 1])).sum()
)

print("\nFinal datatypes:")
print(df_clean.dtypes)

Final Phase 1 shape: (3000, 25)
Missing values: 0
Duplicate rows: 0
Invalid target values: 0

Final datatypes:
date                      datetime64[ns]
user_id                            int64
monthly_income                   float64
monthly_expense_total            float64
savings_rate                     float64
budget_goal                      float64
financial_scenario                object
credit_score                       int64
debt_to_income_ratio             float64
loan_payment                     float64
investment_amount                float64
subscription_services              int64
emergency_fund                   float64
transaction_count                  int64
fraud_flag                         int64
discretionary_spending           float64
essential_spending               float64
income_type                       object
rent_or_mortgage                 float64
category                          object
cash_flow_status                  object
financial_advice_score           float64
financial_stress_level            object
actual_savings                   float64
savings_goal_met                   int64
dtype: object

In [38]:
df_clean.to_csv(
    'phase1_cleaned_finance_dataset.csv',
    index=False
)

print("Phase 1 cleaned dataset saved successfully.")

Phase 1 cleaned dataset saved successfully.

In [39]:
from google.colab import files

files.download(
    'phase1_cleaned_finance_dataset.csv'
)

In [40]:
print(df_clean.shape)
print(df_clean.duplicated().sum())
print(df_clean['date'].isnull().sum())
print(df_clean['savings_goal_met'].value_counts())

(3000, 25)
0
0
savings_goal_met
0    2723
1     277
Name: count, dtype: int64

In [41]:
# phase 2 : data transformation and feature engineering

In [42]:
phase2_df = df_clean.copy()

print("Phase 2 copy created")
print("Shape:", phase2_df.shape)

Phase 2 copy created
Shape: (3000, 25)

In [43]:
important_columns = [
    'date',
    'monthly_income',
    'monthly_expense_total',
    'budget_goal',
    'savings_rate',
    'actual_savings',
    'transaction_count',
    'savings_goal_met'
]

display(phase2_df[important_columns].head(10))

,date,monthly_income,monthly_expense_total,budget_goal,savings_rate,actual_savings,transaction_count,savings_goal_met
0,2019-01-01,3119.58,3212.07,3676.11,0.38,0.00,68,0
1,2019-01-31,3262.44,3732.81,2607.17,0.10,0.00,41,0
2,2019-03-02,2931.20,3335.58,3004.14,0.15,0.00,90,0
3,2019-04-01,3506.79,2327.59,3346.97,0.17,1179.20,94,0
4,2019-05-01,4606.87,2182.58,2670.09,0.34,2424.29,73,0
5,2019-05-31,4028.39,3876.57,2079.72,0.26,151.82,56,0
6,2019-06-30,4145.45,3035.61,2215.80,0.15,1109.84,69,0
7,2019-07-30,3202.37,2689.51,3650.48,0.25,512.86,65,0
8,2019-08-29,4765.11,2628.56,2813.81,0.06,2136.55,99,0
9,2019-09-28,3581.79,3370.80,2195.92,0.13,210.99,91,0

In [44]:
check_df = phase2_df[
    [
        'monthly_income',
        'monthly_expense_total',
        'budget_goal',
        'savings_rate',
        'actual_savings',
        'savings_goal_met'
    ]
].copy()

check_df['calculated_savings'] = (
    check_df['monthly_income']
    - check_df['monthly_expense_total']
)

check_df['actual_savings_difference'] = (
    check_df['actual_savings']
    - check_df['calculated_savings']
).abs()

display(check_df.head(10))

print(
    "Average difference between actual_savings and "
    "income minus expense:",
    check_df['actual_savings_difference'].mean()
)

,monthly_income,monthly_expense_total,budget_goal,savings_rate,actual_savings,savings_goal_met,calculated_savings,actual_savings_difference
0,3119.58,3212.07,3676.11,0.38,0.00,0,-92.49,9.249000e+01
1,3262.44,3732.81,2607.17,0.10,0.00,0,-470.37,4.703700e+02
2,2931.20,3335.58,3004.14,0.15,0.00,0,-404.38,4.043800e+02
3,3506.79,2327.59,3346.97,0.17,1179.20,0,1179.20,2.273737e-13
4,4606.87,2182.58,2670.09,0.34,2424.29,0,2424.29,0.000000e+00
5,4028.39,3876.57,2079.72,0.26,151.82,0,151.82,2.842171e-13
6,4145.45,3035.61,2215.80,0.15,1109.84,0,1109.84,2.273737e-13
7,3202.37,2689.51,3650.48,0.25,512.86,0,512.86,3.410605e-13
8,4765.11,2628.56,2813.81,0.06,2136.55,0,2136.55,4.547474e-13
9,3581.79,3370.80,2195.92,0.13,210.99,0,210.99,2.273737e-13

Average difference between actual_savings and income minus expense: 163.83334000000016

In [45]:
rate_check = phase2_df[
    [
        'monthly_income',
        'actual_savings',
        'savings_rate'
    ]
].copy()

rate_check['calculated_decimal_rate'] = (
    rate_check['actual_savings']
    / rate_check['monthly_income']
)

rate_check['calculated_percentage_rate'] = (
    rate_check['actual_savings']
    / rate_check['monthly_income']
) * 100

decimal_difference = (
    rate_check['savings_rate']
    - rate_check['calculated_decimal_rate']
).abs().mean()

percentage_difference = (
    rate_check['savings_rate']
    - rate_check['calculated_percentage_rate']
).abs().mean()

print("Savings rate minimum:",
      phase2_df['savings_rate'].min())

print("Savings rate maximum:",
      phase2_df['savings_rate'].max())

print("Decimal-rate average difference:",
      decimal_difference)

print("Percentage-rate average difference:",
      percentage_difference)

Savings rate minimum: 0.05
Savings rate maximum: 0.4
Decimal-rate average difference: 0.1925448741739759
Percentage-rate average difference: 25.563095958104196

In [46]:
goal_check = phase2_df[
    [
        'monthly_income',
        'monthly_expense_total',
        'budget_goal',
        'actual_savings',
        'savings_goal_met'
    ]
].copy()

# Possibility 1:
# budget_goal is a savings target
goal_check['result_if_savings_target'] = (
    goal_check['actual_savings']
    >= goal_check['budget_goal']
).astype(int)

# Possibility 2:
# budget_goal is an expense limit
goal_check['result_if_expense_limit'] = (
    goal_check['monthly_expense_total']
    <= goal_check['budget_goal']
).astype(int)

savings_target_agreement = (
    goal_check['result_if_savings_target']
    == goal_check['savings_goal_met']
).mean() * 100

expense_limit_agreement = (
    goal_check['result_if_expense_limit']
    == goal_check['savings_goal_met']
).mean() * 100

print(
    "Agreement if budget_goal is savings_target:",
    round(savings_target_agreement, 2),
    "%"
)

print(
    "Agreement if budget_goal is expense_limit:",
    round(expense_limit_agreement, 2),
    "%"
)

display(goal_check.head(15))

Agreement if budget_goal is savings_target: 100.0 %
Agreement if budget_goal is expense_limit: 60.8 %

,monthly_income,monthly_expense_total,budget_goal,actual_savings,savings_goal_met,result_if_savings_target,result_if_expense_limit
0,3119.58,3212.07,3676.11,0.00,0,0,1
1,3262.44,3732.81,2607.17,0.00,0,0,0
2,2931.20,3335.58,3004.14,0.00,0,0,0
3,3506.79,2327.59,3346.97,1179.20,0,0,1
4,4606.87,2182.58,2670.09,2424.29,0,0,1
5,4028.39,3876.57,2079.72,151.82,0,0,0
6,4145.45,3035.61,2215.80,1109.84,0,0,0
7,3202.37,2689.51,3650.48,512.86,0,0,1
8,4765.11,2628.56,2813.81,2136.55,0,0,1
9,3581.79,3370.80,2195.92,210.99,0,0,0
10,3832.71,3230.77,3178.17,601.94,0,0,0
11,2136.79,3444.29,2685.16,0.00,0,0,0
12,5462.92,3049.29,2973.21,2413.63,0,0,0
13,2110.66,2707.86,1420.73,0.00,0,0,0
14,3507.29,2661.40,3493.12,845.89,0,0,1

In [47]:
goal_check = phase2_df[
    [
        'monthly_income',
        'monthly_expense_total',
        'budget_goal',
        'actual_savings',
        'savings_goal_met'
    ]
].copy()

# Possibility 1:
# budget_goal is a savings target
goal_check['result_if_savings_target'] = (
    goal_check['actual_savings']
    >= goal_check['budget_goal']
).astype(int)

# Possibility 2:
# budget_goal is an expense limit
goal_check['result_if_expense_limit'] = (
    goal_check['monthly_expense_total']
    <= goal_check['budget_goal']
).astype(int)

savings_target_agreement = (
    goal_check['result_if_savings_target']
    == goal_check['savings_goal_met']
).mean() * 100

expense_limit_agreement = (
    goal_check['result_if_expense_limit']
    == goal_check['savings_goal_met']
).mean() * 100

print(
    "Agreement if budget_goal is savings_target:",
    round(savings_target_agreement, 2),
    "%"
)

print(
    "Agreement if budget_goal is expense_limit:",
    round(expense_limit_agreement, 2),
    "%"
)

display(goal_check.head(15))

Agreement if budget_goal is savings_target: 100.0 %
Agreement if budget_goal is expense_limit: 60.8 %

,monthly_income,monthly_expense_total,budget_goal,actual_savings,savings_goal_met,result_if_savings_target,result_if_expense_limit
0,3119.58,3212.07,3676.11,0.00,0,0,1
1,3262.44,3732.81,2607.17,0.00,0,0,0
2,2931.20,3335.58,3004.14,0.00,0,0,0
3,3506.79,2327.59,3346.97,1179.20,0,0,1
4,4606.87,2182.58,2670.09,2424.29,0,0,1
5,4028.39,3876.57,2079.72,151.82,0,0,0
6,4145.45,3035.61,2215.80,1109.84,0,0,0
7,3202.37,2689.51,3650.48,512.86,0,0,1
8,4765.11,2628.56,2813.81,2136.55,0,0,1
9,3581.79,3370.80,2195.92,210.99,0,0,0
10,3832.71,3230.77,3178.17,601.94,0,0,0
11,2136.79,3444.29,2685.16,0.00,0,0,0
12,5462.92,3049.29,2973.21,2413.63,0,0,0
13,2110.66,2707.86,1420.73,0.00,0,0,0
14,3507.29,2661.40,3493.12,845.89,0,0,1

In [48]:
print(
    "Average actual_savings difference:",
    check_df['actual_savings_difference'].mean()
)

print(
    "Decimal-rate average difference:",
    decimal_difference
)

print(
    "Percentage-rate average difference:",
    percentage_difference
)

print(
    "Agreement if budget_goal is savings_target:",
    round(savings_target_agreement, 2),
    "%"
)

print(
    "Agreement if budget_goal is expense_limit:",
    round(expense_limit_agreement, 2),
    "%"
)

Average actual_savings difference: 163.83334000000016
Decimal-rate average difference: 0.1925448741739759
Percentage-rate average difference: 25.563095958104196
Agreement if budget_goal is savings_target: 100.0 %
Agreement if budget_goal is expense_limit: 60.8 %

In [49]:
final_df = pd.DataFrame()

print("Empty final dataset created")

Empty final dataset created

In [50]:
# Existing date will be treated as the prediction date
final_df['prediction_date'] = pd.to_datetime(
    phase2_df['date'],
    errors='coerce'
)

# Extract year
final_df['year'] = final_df['prediction_date'].dt.year

# Extract month name
final_df['month'] = final_df['prediction_date'].dt.month_name()

In [51]:
final_df['income_received_date'] = (
    final_df['prediction_date']
    .dt.to_period('M')
    .dt.to_timestamp()
)

In [52]:
final_df['income_amount'] = phase2_df['monthly_income']

final_df['savings_target'] = phase2_df['budget_goal']

final_df['amount_spent_so_far'] = (
    phase2_df['monthly_expense_total']
)

final_df['transaction_count'] = (
    phase2_df['transaction_count']
)

final_df['target_achieved'] = (
    phase2_df['savings_goal_met'].astype(int)
)

In [53]:
final_df['expense_limit'] = (
    final_df['income_amount']
    - final_df['savings_target']
)

In [54]:
final_df['remaining_budget'] = (
    final_df['expense_limit']
    - final_df['amount_spent_so_far']
)

In [55]:
final_df['budget_used_percentage'] = np.where(
    final_df['expense_limit'] > 0,
    (
        final_df['amount_spent_so_far']
        / final_df['expense_limit']
    ) * 100,
    np.nan
)

In [56]:
final_df['budget_used_percentage'] = (
    final_df['budget_used_percentage'].round(2)
)

In [57]:
days_in_month = (
    final_df['prediction_date'].dt.days_in_month
)

current_day = (
    final_df['prediction_date'].dt.day
)

final_df['days_remaining'] = (
    days_in_month - current_day
)

In [58]:
final_columns = [
    'year',
    'month',
    'income_received_date',
    'prediction_date',
    'income_amount',
    'expense_limit',
    'savings_target',
    'amount_spent_so_far',
    'transaction_count',
    'remaining_budget',
    'budget_used_percentage',
    'days_remaining',
    'target_achieved'
]

final_df = final_df[final_columns]

In [59]:
display(final_df.head(10))

,year,month,income_received_date,prediction_date,income_amount,expense_limit,savings_target,amount_spent_so_far,transaction_count,remaining_budget,budget_used_percentage,days_remaining,target_achieved
0,2019,January,2019-01-01,2019-01-01,3119.58,-556.53,3676.11,3212.07,68,-3768.60,NaN,30,0
1,2019,January,2019-01-01,2019-01-31,3262.44,655.27,2607.17,3732.81,41,-3077.54,569.66,0,0
2,2019,March,2019-03-01,2019-03-02,2931.20,-72.94,3004.14,3335.58,90,-3408.52,NaN,29,0
3,2019,April,2019-04-01,2019-04-01,3506.79,159.82,3346.97,2327.59,94,-2167.77,1456.38,29,0
4,2019,May,2019-05-01,2019-05-01,4606.87,1936.78,2670.09,2182.58,73,-245.80,112.69,30,0
5,2019,May,2019-05-01,2019-05-31,4028.39,1948.67,2079.72,3876.57,56,-1927.90,198.93,0,0
6,2019,June,2019-06-01,2019-06-30,4145.45,1929.65,2215.80,3035.61,69,-1105.96,157.31,0,0
7,2019,July,2019-07-01,2019-07-30,3202.37,-448.11,3650.48,2689.51,65,-3137.62,NaN,1,0
8,2019,August,2019-08-01,2019-08-29,4765.11,1951.30,2813.81,2628.56,99,-677.26,134.71,2,0
9,2019,September,2019-09-01,2019-09-28,3581.79,1385.87,2195.92,3370.80,91,-1984.93,243.23,2,0

In [60]:
print("Final shape:", final_df.shape)

print(
    "Total missing values:",
    final_df.isnull().sum().sum()
)

print(
    "Invalid target values:",
    (~final_df['target_achieved'].isin([0, 1])).sum()
)

print(
    "Invalid expense limits:",
    (final_df['expense_limit'] <= 0).sum()
)

print(
    "Negative transaction counts:",
    (final_df['transaction_count'] < 0).sum()
)

Final shape: (3000, 13)
Total missing values: 413
Invalid target values: 0
Invalid expense limits: 413
Negative transaction counts: 0

In [61]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    3000 non-null   int32
 1   month                   3000 non-null   object
 2   income_received_date    3000 non-null   datetime64[ns]
 3   prediction_date         3000 non-null   datetime64[ns]
 4   income_amount           3000 non-null   float64
 5   expense_limit           3000 non-null   float64
 6   savings_target          3000 non-null   float64
 7   amount_spent_so_far     3000 non-null   float64
 8   transaction_count       3000 non-null   int64
 9   remaining_budget        3000 non-null   float64
 10  budget_used_percentage  2587 non-null   float64
 11  days_remaining          3000 non-null   int32
 12  target_achieved         3000 non-null   int64
dtypes: datetime64[ns](2), float64(6), int32(2), int64(2), object(1)
memory usage: 281.4+ KB

In [62]:
print(final_df['target_achieved'].value_counts())

print(
    final_df['target_achieved']
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

target_achieved
0    2723
1     277
Name: count, dtype: int64
target_achieved
0    90.77
1     9.23
Name: proportion, dtype: float64

In [63]:
invalid_plan = final_df[
    (
        final_df['expense_limit']
        + final_df['savings_target']
    )
    > final_df['income_amount']
]

print("Invalid financial plans:", len(invalid_plan))

Invalid financial plans: 7

In [64]:
# 1. Check the original difference
final_df['plan_difference'] = (
    final_df['expense_limit']
    + final_df['savings_target']
    - final_df['income_amount']
)

display(
    final_df[
        final_df['plan_difference'] > 0
    ][[
        'income_amount',
        'expense_limit',
        'savings_target',
        'plan_difference'
    ]]
)

      income_amount  expense_limit  savings_target  plan_difference
387          826.36       -1380.61         2206.97     1.136868e-13
476         1117.36       -2783.79         3901.15     2.273737e-13
958         6577.71        4343.10         2234.61     9.094947e-13
1066        6707.56        5001.04         1706.52     9.094947e-13
1648        3883.98        2106.26         1777.72     4.547474e-13
1728        3965.61        2122.85         1842.76     4.547474e-13
2453        3970.14        2112.13         1858.01     4.547474e-13

In [65]:
# 2. Round all money columns
money_columns = [
    'income_amount',
    'expense_limit',
    'savings_target',
    'amount_spent_so_far',
    'remaining_budget'
]

final_df[money_columns] = final_df[money_columns].round(2)

In [66]:
# 3. Recalculate the difference after rounding
final_df['plan_difference'] = (
    final_df['expense_limit']
    + final_df['savings_target']
    - final_df['income_amount']
).round(2)

In [67]:
# 4. Validate using one-paisa tolerance
tolerance = 0.01

invalid_plan = final_df[
    final_df['plan_difference'] > tolerance
]

print("Truly invalid financial plans:", len(invalid_plan))

Truly invalid financial plans: 0

In [68]:
# 5. Perform additional checks
print(
    "Savings target greater than income:",
    (
        final_df['savings_target']
        > final_df['income_amount']
    ).sum()
)

print(
    "Zero or negative expense limits:",
    (
        final_df['expense_limit'] <= 0
    ).sum()
)

Savings target greater than income: 413
Zero or negative expense limits: 413

In [69]:
# 6. Remove the temporary checking column
final_df.drop(
    columns='plan_difference',
    inplace=True
)

In [70]:
money_columns = [
    'income_amount',
    'expense_limit',
    'savings_target',
    'amount_spent_so_far',
    'remaining_budget'
]

final_df[money_columns] = final_df[money_columns].round(2)

In [71]:
print("Shape:", final_df.shape)
print("Total missing values:", final_df.isnull().sum().sum())
print("Duplicate rows:", final_df.duplicated().sum())

print("\nColumns:")
print(final_df.columns.tolist())

display(final_df.head())

final_df.info()

Shape: (3000, 13)
Total missing values: 413
Duplicate rows: 0

Columns:
['year', 'month', 'income_received_date', 'prediction_date', 'income_amount', 'expense_limit', 'savings_target', 'amount_spent_so_far', 'transaction_count', 'remaining_budget', 'budget_used_percentage', 'days_remaining', 'target_achieved']

,year,month,income_received_date,prediction_date,income_amount,expense_limit,savings_target,amount_spent_so_far,transaction_count,remaining_budget,budget_used_percentage,days_remaining,target_achieved
0,2019,January,2019-01-01,2019-01-01,3119.58,-556.53,3676.11,3212.07,68,-3768.60,NaN,30,0
1,2019,January,2019-01-01,2019-01-31,3262.44,655.27,2607.17,3732.81,41,-3077.54,569.66,0,0
2,2019,March,2019-03-01,2019-03-02,2931.20,-72.94,3004.14,3335.58,90,-3408.52,NaN,29,0
3,2019,April,2019-04-01,2019-04-01,3506.79,159.82,3346.97,2327.59,94,-2167.77,1456.38,29,0
4,2019,May,2019-05-01,2019-05-01,4606.87,1936.78,2670.09,2182.58,73,-245.80,112.69,30,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    3000 non-null   int32
 1   month                   3000 non-null   object
 2   income_received_date    3000 non-null   datetime64[ns]
 3   prediction_date         3000 non-null   datetime64[ns]
 4   income_amount           3000 non-null   float64
 5   expense_limit           3000 non-null   float64
 6   savings_target          3000 non-null   float64
 7   amount_spent_so_far     3000 non-null   float64
 8   transaction_count       3000 non-null   int64
 9   remaining_budget        3000 non-null   float64
 10  budget_used_percentage  2587 non-null   float64
 11  days_remaining          3000 non-null   int32
 12  target_achieved         3000 non-null   int64
dtypes: datetime64[ns](2), float64(6), int32(2), int64(2), object(1)
memory usage: 281.4+ KB

In [72]:
print("plan_difference" in final_df.columns)

False

In [73]:
final_df.to_csv(
    'phase2_transformed_finance_dataset.csv',
    index=False
)

print("Phase 2 dataset saved successfully")

Phase 2 dataset saved successfully

In [74]:
from google.colab import files

files.download(
    'phase2_transformed_finance_dataset.csv'
)

In [ ]:
# before EDA

In [75]:
print("Dataset shape:", final_df.shape)

print(
    "Missing values:",
    final_df.isnull().sum().sum()
)

print(
    "Exact duplicate rows:",
    final_df.duplicated().sum()
)

print(
    "Invalid expense limits:",
    (final_df['expense_limit'] <= 0).sum()
)

print(
    "Negative transaction counts:",
    (final_df['transaction_count'] < 0).sum()
)

print(
    "Invalid target values:",
    (~final_df['target_achieved'].isin([0, 1])).sum()
)

print(
    "Income date after prediction date:",
    (
        final_df['income_received_date']
        > final_df['prediction_date']
    ).sum()
)

print("\nTarget distribution:")
print(final_df['target_achieved'].value_counts())

print("\nTarget percentage:")
print(
    final_df['target_achieved']
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Dataset shape: (3000, 13)
Missing values: 413
Exact duplicate rows: 0
Invalid expense limits: 413
Negative transaction counts: 0
Invalid target values: 0
Income date after prediction date: 0

Target distribution:
target_achieved
0    2723
1     277
Name: count, dtype: int64

Target percentage:
target_achieved
0    90.77
1     9.23
Name: proportion, dtype: float64

In [76]:
print(
    "Earliest prediction date:",
    final_df['prediction_date'].min()
)

print(
    "Latest prediction date:",
    final_df['prediction_date'].max()
)

print(
    "Minimum days remaining:",
    final_df['days_remaining'].min()
)

print(
    "Maximum days remaining:",
    final_df['days_remaining'].max()
)

Earliest prediction date: 2019-01-01 00:00:00
Latest prediction date: 2023-11-06 00:00:00
Minimum days remaining: 0
Maximum days remaining: 30